"""add body composition fields

Revision ID: fb0db5c0c33b
Revises: 6e54e2dd45a5
Create Date: 2026-06-20 14:26:36.668867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb0db5c0c33b'
down_revision: Union[str, None] = '6e54e2dd45a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('body_measurements', sa.Column('bmi', sa.Float(), nullable=True))
    op.add_column('body_measurements', sa.Column('fat_mass_kg', sa.Float(), nullable=True))
    op.add_column('body_measurements', sa.Column('lean_mass_kg', sa.Float(), nullable=True))
    op.add_column('body_measurements', sa.Column('skeletal_muscle_kg', sa.Float(), nullable=True))
    op.add_column('body_measurements', sa.Column('fat_free_weight_kg', sa.Float(), nullable=True))
    op.add_column('body_measurements', sa.Column('body_water_pct', sa.Float(), nullable=True))
    op.add_column('body_measurements', sa.Column('protein_kg', sa.Float(), nullable=True))
    op.add_column('body_measurements', sa.Column('inorganic_salt_kg', sa.Float(), nullable=True))
    op.add_column('body_measurements', sa.Column('bmr_kcal', sa.Float(), nullable=True))
    op.add_column('body_measurements', sa.Column('visceral_fat_grade', sa.Float(), nullable=True))
    op.add_column('body_measurements', sa.Column('subcutaneous_fat_pct', sa.Float(), nullable=True))
    op.add_column('body_measurements', sa.Column('body_age', sa.Integer(), nullable=True))
    op.add_column('body_measurements', sa.Column('whr_estimate', sa.Float(), nullable=True))
    op.add_column('body_measurements', sa.Column('smi', sa.Float(), nullable=True))
    op.add_column('body_measurements', sa.Column('ra_fat_kg', sa.Float(), nullable=True))
    op.add_column('body_measurements', sa.Column('la_fat_kg', sa.Float(), nullable=True))
    op.add_column('body_measurements', sa.Column('trunk_fat_kg', sa.Float(), nullable=True))
    op.add_column('body_measurements', sa.Column('rl_fat_kg', sa.Float(), nullable=True))
    op.add_column('body_measurements', sa.Column('ll_fat_kg', sa.Float(), nullable=True))
    op.add_column('body_measurements', sa.Column('ra_muscle_kg', sa.Float(), nullable=True))
    op.add_column('body_measurements', sa.Column('la_muscle_kg', sa.Float(), nullable=True))
    op.add_column('body_measurements', sa.Column('trunk_muscle_kg', sa.Float(), nullable=True))
    op.add_column('body_measurements', sa.Column('rl_muscle_kg', sa.Float(), nullable=True))
    op.add_column('body_measurements', sa.Column('ll_muscle_kg', sa.Float(), nullable=True))
    op.add_column('body_measurements', sa.Column('ra_z20', sa.Float(), nullable=True))
    op.add_column('body_measurements', sa.Column('la_z20', sa.Float(), nullable=True))
    op.add_column('body_measurements', sa.Column('rl_z20', sa.Float(), nullable=True))
    op.add_column('body_measurements', sa.Column('ll_z20', sa.Float(), nullable=True))
    op.add_column('body_measurements', sa.Column('trunk_z20', sa.Float(), nullable=True))
    op.add_column('body_measurements', sa.Column('ra_z100', sa.Float(), nullable=True))
    op.add_column('body_measurements', sa.Column('la_z100', sa.Float(), nullable=True))
    op.add_column('body_measurements', sa.Column('rl_z100', sa.Float(), nullable=True))
    op.add_column('body_measurements', sa.Column('ll_z100', sa.Float(), nullable=True))
    op.add_column('body_measurements', sa.Column('trunk_z100', sa.Float(), nullable=True))
    op.drop_column('body_measurements', 'bone_mass_kg')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('body_measurements', sa.Column('bone_mass_kg', sa.FLOAT(), nullable=True))
    op.drop_column('body_measurements', 'trunk_z100')
    op.drop_column('body_measurements', 'll_z100')
    op.drop_column('body_measurements', 'rl_z100')
    op.drop_column('body_measurements', 'la_z100')
    op.drop_column('body_measurements', 'ra_z100')
    op.drop_column('body_measurements', 'trunk_z20')
    op.drop_column('body_measurements', 'll_z20')
    op.drop_column('body_measurements', 'rl_z20')
    op.drop_column('body_measurements', 'la_z20')
    op.drop_column('body_measurements', 'ra_z20')
    op.drop_column('body_measurements', 'll_muscle_kg')
    op.drop_column('body_measurements', 'rl_muscle_kg')
    op.drop_column('body_measurements', 'trunk_muscle_kg')
    op.drop_column('body_measurements', 'la_muscle_kg')
    op.drop_column('body_measurements', 'ra_muscle_kg')
    op.drop_column('body_measurements', 'll_fat_kg')
    op.drop_column('body_measurements', 'rl_fat_kg')
    op.drop_column('body_measurements', 'trunk_fat_kg')
    op.drop_column('body_measurements', 'la_fat_kg')
    op.drop_column('body_measurements', 'ra_fat_kg')
    op.drop_column('body_measurements', 'smi')
    op.drop_column('body_measurements', 'whr_estimate')
    op.drop_column('body_measurements', 'body_age')
    op.drop_column('body_measurements', 'subcutaneous_fat_pct')
    op.drop_column('body_measurements', 'visceral_fat_grade')
    op.drop_column('body_measurements', 'bmr_kcal')
    op.drop_column('body_measurements', 'inorganic_salt_kg')
    op.drop_column('body_measurements', 'protein_kg')
    op.drop_column('body_measurements', 'body_water_pct')
    op.drop_column('body_measurements', 'fat_free_weight_kg')
    op.drop_column('body_measurements', 'skeletal_muscle_kg')
    op.drop_column('body_measurements', 'lean_mass_kg')
    op.drop_column('body_measurements', 'fat_mass_kg')
    op.drop_column('body_measurements', 'bmi')
    # ### end Alembic commands ###
